apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: health-check
      namespace: build
      labels:
        build: health-check

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: health-check
      namespace: build
      labels:
        build: health-check
    spec:
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile
      source:
        type: Binary
      output:
        to:
          kind: ImageStreamTag
          # TODO put a placeholder in the version and replace before oc apply
          name: "health-check:0.0.1"
      runPolicy: Serial
      triggers: []
