apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: health-check
      labels:
        app: health-check
    spec:
      replicas: 1
      selector:
        app: health-check
        deploymentconfig: health-check
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: health-check
            deploymentconfig: health-check
        spec:
          containers:
            - name: health-check
              imagePullPolicy: Always
              ports:
                - name: api
                  containerPort: 8086
              resources:
                requests:
                  cpu: 25m
                  memory: 50Mi
                limits:
                  cpu: 1
                  memory: 500Mi
              nodeSelector:
                node_type: app
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - type: ImageChange
          automatic: false
          imageChangeParams:
            containerNames:
              - health-check
            from:
              kind: ImageStreamTag
              name: 'health-check:0.0.1'


  - apiVersion: v1
    kind: Service
    metadata:
      name: health-check
      labels:
        app: health-check
    spec:
      type: ClusterIP
      ports:
        - name: https
          port: 443
          protocol: TCP
          targetPort: 8086
      selector:
        app: health-check
        deploymentconfig: health-check

  - apiVersion: v1
    kind: Route
    metadata:
      name: health-check
    spec:
      host: platform-health-check.seiyu.launcherbot.com
      path: /
      port:
        targetPort: https
      tls:
        insecureEdgeTerminationPolicy: Allow
        termination: edge
      to:
        kind: Service
        name: health-check
        weight: 100
      wildcardPolicy: None