apiVersion: v1
kind: List
items:

  - apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      name: health-check-stflset
      labels:
        app: health-check
        project: build
        env: prod
    spec:
      replicas: 1
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: health-check
        spec:
          containers:
            - name: health-check-stflset
              imagePullPolicy: Always
              ports:
                - name: api
                  containerPort: 8080
              resources:
                requests:
                  cpu: 25m
                  memory: 50Mi
                limits:
                  cpu: 1
                  memory: 500Mi
              nodeSelector:
                node_type: app
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - type: ImageChange
          automatic: false
          imageChangeParams:
            containerNames:
              - health-check
            from:
              kind: ImageStreamTag
              name: 'health-check:latest'


  - apiVersion: v1
    kind: Service
    metadata:
      name: health-check-stflset
      labels:
        app: health-check
    spec:
      type: ClusterIP
      ports:
        - name: https
          port: 443
          protocol: TCP
          targetPort: 8080
      selector:
        app: health-check

  - apiVersion: v1
    kind: Route
    metadata:
      name: health-check-stflset
    spec:
      host: health-stflset.test-platform-engineering.club
      path: /
      port:
        targetPort: https
      tls:
        insecureEdgeTerminationPolicy: Allow
        termination: edge
      to:
        kind: Service
        name: health-check
        weight: 100
      wildcardPolicy: None