apiVersion: v1
kind: List
items:

  - apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      name: health-check-podid-test
      labels:
        app: health-check-podid-test
        project: build
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: "health-check-podid-test"
      serviceName: "health-check-podid-test"
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
      template:
        metadata:
          labels:
            app: health-check-podid-test
            project: build
        spec:
          containers:
            - name: health-check-podid-test
              image: "docker-registry.default.svc:5000/build/health-check:0.0.7"
              imagePullPolicy: Always
              ports:
                - name: api-stf
                  containerPort: 8080
              resources:
                requests:
                  cpu: 25m
                  memory: 50Mi
                limits:
                  cpu: 1
                  memory: 500Mi
              nodeSelector:
                node_type: app
          dnsPolicy: ClusterFirst
          restartPolicy: Always


  - apiVersion: v1
    kind: Service
    metadata:
      name: health-check-podid-test
      labels:
        app: health-check-podid-test
    spec:
      type: ClusterIP
      ports:
        - name: https
          port: 443
          protocol: TCP
          targetPort: 8080
      selector:
        app: health-check-podid-test

  - apiVersion: v1
    kind: Route
    metadata:
      name: health-check-podid-test
    spec:
      host: health-stflset.seiyu.launcherbot.com
      path: /
      port:
        targetPort: https
      tls:
        insecureEdgeTerminationPolicy: Allow
        termination: edge
      to:
        kind: Service
        name: health-check-podid-test
        weight: 100
      wildcardPolicy: None